(function () {
  const pages = window.HamLogPages = window.HamLogPages || {}; const {escapeHtml, formatNumber} = HamLogUtils;
  pages.adif = async function adifPage(container) {
    container.innerHTML = `<div class="page-heading"><div><p class="eyebrow">Interchange</p><h1>ADIF 导出</h1><p>将日志导出为可用于 LoTW、第三方日志软件的 ADIF 文件。</p></div></div><section class="panel"><div class="panel-header"><div><h2>导出范围</h2><p>筛选条件由后端应用到导出查询。</p></div></div><form id="adif-form"><div class="form-grid"><label>开始日期<input type="date" name="date_from"></label><label>结束日期<input type="date" name="date_to"></label><label>波段<input name="band" placeholder="例如 2m"></label><label>模式<select name="mode"><option value="">全部模式</option><option>SSB</option><option>CW</option><option>FM</option><option>FT8</option><option>FT4</option></select></label><label>本台呼号<input name="station_callsign" value=""></label></div><div class="form-actions"><button class="button button-primary" type="submit">生成 ADIF</button></div></form></section><section class="panel" id="adif-result"><div class="table-empty">尚未生成导出文件。</div></section><section class="panel"><div class="panel-header"><div><h2>ADIF 说明</h2><p>数据映射与当前后端能力</p></div></div><div class="result-grid"><div class="result-item"><dt>呼号</dt><dd>CALL</dd></div><div class="result-item"><dt>频率</dt><dd>FREQ</dd></div><div class="result-item"><dt>模式</dt><dd>MODE</dd></div><div class="result-item"><dt>信号报告</dt><dd>RST_SENT / RST_RCVD</dd></div><div class="result-item"><dt>QTH</dt><dd>QTH</dd></div><div class="result-item"><dt>备注</dt><dd>COMMENT</dd></div></div></section>`;
    const form = document.querySelector('#adif-form'); const result = document.querySelector('#adif-result');
    try { const settings = await HamLogAPI.post('/settings/get_all'); form.elements.station_callsign.value = settings.my_callsign || ''; } catch (_) { /* optional station default */ }
    form.onsubmit = async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); result.innerHTML = '<div class="loading">正在生成 ADIF...</div>'; try { const exportData = await HamLogAPI.post('/adif/export', Object.assign(data, {band: data.band || null, mode: data.mode || null})); result.innerHTML = `<div class="panel-header"><div><h2>导出已准备</h2><p>文件可下载一次，令牌过期后请重新生成。</p></div><span class="badge success">${formatNumber(exportData.exported || 0)} 条</span></div><div class="result-grid"><div class="result-item"><dt>扫描记录</dt><dd>${formatNumber(exportData.total)}</dd></div><div class="result-item"><dt>已导出</dt><dd>${formatNumber(exportData.exported)}</dd></div><div class="result-item"><dt>跳过</dt><dd>${formatNumber(exportData.skipped)}</dd></div><div class="result-item"><dt>错误</dt><dd>${formatNumber((exportData.errors || []).length)}</dd></div></div><div class="form-actions"><button class="button button-primary" id="download-adif">下载 hamlog.adi</button></div>`; document.querySelector('#download-adif').onclick = async () => { try { await HamLogAPI.download('/adif/download', {token: exportData.token}, 'hamlog.adi'); HamLogToast.show('ADIF 下载已开始'); } catch (error) { HamLogToast.error(error.message); } }; } catch (error) { result.innerHTML = `<div class="notice danger">${escapeHtml(error.message)}</div>`; } };
  };
}());
