(function () {
  const pages = window.HamLogPages = window.HamLogPages || {}; const {escapeHtml} = HamLogUtils;
  pages.network = async function networkPage(container) {
    const config = await HamLogAPI.post('/intertime/get');
    container.innerHTML = `<div class="page-heading"><div><p class="eyebrow">Network telemetry</p><h1>网络监测</h1><p>定时检测多节点 TCP 建连延迟。</p></div><span id="monitor-badge" class="badge ${config.enabled ? 'success' : ''}">${config.enabled ? '轮询已启用' : '轮询已停止'}</span></div><section class="panel"><div class="panel-header"><div><h2>监测配置</h2><p>节点支持域名、IP 或 host:port；未指定端口时使用 443。</p></div><div class="toolbar-action"><button class="button button-secondary button-small" id="test-network">立即检测</button><button class="button button-primary button-small" id="toggle-network">${config.enabled ? '停止轮询' : '启动轮询'}</button></div></div><form id="network-form"><div class="form-grid"><label>监测节点<input name="nodes" value="${escapeHtml((config.nodes || []).join(', '))}" placeholder="www.baidu.com:443, 8.8.8.8:53"></label><label>超时（秒）<input type="number" name="timeout" min="0.1" step="0.1" max="30" value="${escapeHtml(config.timeout || 2)}"></label><label>间隔（秒）<input type="number" name="interval" min="1" max="3600" value="${escapeHtml(config.interval || 5)}"></label><label>显示名称<input name="display_names" value="${escapeHtml(Object.entries(config.display_names || {}).map(([key, value]) => `${key}=${value}`).join(', '))}" placeholder="www.baidu.com:443=百度"></label></div><div class="form-actions"><button class="button button-secondary" type="submit">保存配置</button></div></form></section><section class="panel"><div class="panel-header"><div><h2>节点状态</h2><p id="network-updated">尚未检测</p></div></div><div id="network-results" class="table-empty">点击“立即检测”开始。</div></section>`;
    const form = document.querySelector('#network-form'); const results = document.querySelector('#network-results'); let pollTimer;
    function payload() { const data = Object.fromEntries(new FormData(form)); const display_names = {}; (data.display_names || '').split(',').map(item => item.trim()).filter(Boolean).forEach(item => { const split = item.indexOf('='); if (split > 0) display_names[item.slice(0, split).trim()] = item.slice(split + 1).trim(); }); return {enabled: config.enabled, nodes:data.nodes.split(',').map(node => node.trim()).filter(Boolean), timeout:Number(data.timeout), interval:Number(data.interval), display_names}; }
    async function test() { results.innerHTML = '<div class="loading">检测节点中...</div>'; try { const data = await HamLogAPI.post('/intertime/test', {nodes:payload().nodes, timeout:payload().timeout}); results.innerHTML = `<div class="table-wrap"><table><thead><tr><th>节点</th><th>显示名称</th><th>延迟</th><th>状态</th></tr></thead><tbody>${(data.results || []).map(item => `<tr><td>${escapeHtml(item.node)}</td><td>${escapeHtml(payload().display_names[item.node] || '-')}</td><td>${item.time_ms == null ? '-' : `${item.time_ms} ms`}</td><td><span class="badge ${item.ok ? 'success' : 'danger'}">${item.ok ? '可达' : '失败'}</span></td></tr>`).join('')}</tbody></table></div>`; document.querySelector('#network-updated').textContent = `最近检测：${new Date().toLocaleTimeString('zh-CN')}`; } catch (error) { results.innerHTML = `<div class="notice danger">${escapeHtml(error.message)}</div>`; } }
    form.onsubmit = async event => { event.preventDefault(); try { const saved = await HamLogAPI.post('/intertime/set', payload()); Object.assign(config, saved); HamLogToast.show('监测配置已保存'); } catch (error) { HamLogToast.error(error.message); } };
    document.querySelector('#test-network').onclick = test; document.querySelector('#toggle-network').onclick = async () => { try { const next = config.enabled ? await HamLogAPI.post('/intertime/stop') : await HamLogAPI.post('/intertime/start'); config.enabled = next.enabled; document.querySelector('#monitor-badge').textContent = config.enabled ? '轮询已启用' : '轮询已停止'; document.querySelector('#monitor-badge').className = `badge ${config.enabled ? 'success' : ''}`; document.querySelector('#toggle-network').textContent = config.enabled ? '停止轮询' : '启动轮询'; } catch (error) { HamLogToast.error(error.message); } };
    if (config.enabled) { await test(); pollTimer = setInterval(test, Math.max(2, Number(config.interval || 5)) * 1000); }
    return () => clearInterval(pollTimer);
  };
}());
