(function () {
  const pages = window.HamLogPages = window.HamLogPages || {};
  const {escapeHtml, formatNumber, debounce} = HamLogUtils;
  const fields = ['Callsign','Freq','Year','Month','Day','Time','Mode','Power_self','Power_side','Rst_self','Rst_side','QTH','Device','QSL_RX','QSL_SEND','Remarks'];
  let state = {page: 1, pageSize: 25, keyword: '', band: '', mode: '', dateFrom: '', dateTo: ''};

  function editorMarkup() {
    const now = new Date();
    return `<section class="panel" id="log-editor" hidden><div class="panel-header"><div><h2 id="editor-title">录入 QSO</h2><p>日期与时间按 UTC 保存，呼号会自动转为大写。</p></div><button class="icon-button" id="close-editor" aria-label="关闭">×</button></div><form id="log-form"><input type="hidden" name="id"><div class="form-grid"><label>对方呼号<input name="Callsign" maxlength="20" required autocomplete="off"></label><label>频率<input name="Freq" placeholder="14.074MHz"></label><label>模式<select name="Mode"><option value="">选择模式</option><option>SSB</option><option>CW</option><option>FM</option><option>AM</option><option>FT8</option><option>FT4</option><option>RTTY</option><option>DIGI</option></select></label><label>UTC 日期<input name="qso_date" type="date" value="${now.toISOString().slice(0,10)}" required></label><label>UTC 时间<input name="Time" inputmode="numeric" pattern="[0-9]{4,6}" value="${String(now.getUTCHours()).padStart(2,'0')}${String(now.getUTCMinutes()).padStart(2,'0')}" required></label><label>本台功率<input name="Power_self" placeholder="5W"></label><label>对方功率<input name="Power_side" placeholder="未知"></label><label>设备<input name="Device" placeholder="FT-817"></label><label>发送 RST<input name="Rst_self" placeholder="59"></label><label>接收 RST<input name="Rst_side" placeholder="59"></label><label>QTH<input name="QTH" placeholder="Chengdu"></label><label>QSL 接收<input name="QSL_RX" placeholder="YYYYMMDD / 状态"></label><label>QSL 发送<input name="QSL_SEND" placeholder="YYYYMMDD / 状态"></label><label style="grid-column:span 3">备注<input name="Remarks" placeholder="设备、天线或通联备注"></label></div><div class="form-actions"><button type="button" class="button button-secondary" id="cancel-editor">取消</button><button class="button button-primary" type="submit">保存记录</button></div></form></section>`;
  }

  pages.logs = async function logsPage(container, params) {
    container.innerHTML = `<div class="page-heading"><div><p class="eyebrow">QSO Logbook</p><h1>QSO 日志</h1><p>录入、检索并维护电台通联记录。</p></div><button class="button button-primary" id="new-log">＋ 录入 QSO</button></div><div id="log-stats" class="stats-grid"><div class="loading">加载统计...</div></div>${editorMarkup()}<section class="panel"><div class="panel-header"><div><h2>日志记录</h2><p>支持呼号、QTH、设备与备注模糊搜索</p></div></div><div class="toolbar"><label>搜索<input id="log-keyword" placeholder="呼号、QTH、设备或备注" value="${escapeHtml(state.keyword)}"></label><label>波段<select id="log-band"><option value="">全部波段</option>${['160m','80m','40m','20m','15m','10m','6m','2m','70cm','23cm'].map(band => `<option${state.band === band ? ' selected' : ''}>${band}</option>`).join('')}</select></label><label>模式<select id="log-mode"><option value="">全部模式</option>${['SSB','CW','FM','AM','FT8','FT4','RTTY','DIGI'].map(mode => `<option${state.mode === mode ? ' selected' : ''}>${mode}</option>`).join('')}</select></label><label>开始日期<input id="log-from" type="date" value="${escapeHtml(state.dateFrom)}"></label><label>结束日期<input id="log-to" type="date" value="${escapeHtml(state.dateTo)}"></label><div class="toolbar-action"><button class="button button-secondary" id="reset-search">重置</button><button class="button button-primary" id="run-search">搜索</button></div></div><div id="logs-table" class="loading">加载日志...</div></section>`;
    const editor = document.querySelector('#log-editor'); const form = document.querySelector('#log-form');
    function closeEditor() { editor.hidden = true; form.reset(); form.elements.id.value = ''; }
    function openEditor(item) {
      editor.hidden = false; document.querySelector('#editor-title').textContent = item ? `编辑 ${item.Callsign}` : '录入 QSO'; form.reset();
      if (item) { fields.forEach(field => { if (form.elements[field]) form.elements[field].value = item[field] == null ? '' : item[field]; }); form.elements.id.value = item.id; form.elements.qso_date.value = [item.Year, String(item.Month || '').padStart(2,'0'), String(item.Day || '').padStart(2,'0')].join('-'); }
      else { const now = new Date(); form.elements.qso_date.value = now.toISOString().slice(0,10); form.elements.Time.value = `${String(now.getUTCHours()).padStart(2,'0')}${String(now.getUTCMinutes()).padStart(2,'0')}`; }
      editor.scrollIntoView({behavior:'smooth', block:'start'}); setTimeout(() => form.elements.Callsign.focus(), 250);
    }
    document.querySelector('#new-log').onclick = () => openEditor(); document.querySelector('#close-editor').onclick = closeEditor; document.querySelector('#cancel-editor').onclick = closeEditor;
    form.elements.Callsign.addEventListener('input', event => { const start = event.target.selectionStart; event.target.value = event.target.value.toUpperCase(); event.target.setSelectionRange(start, start); });
    async function loadStats() {
      const stats = await HamLogAPI.post('/log/stats'); document.querySelector('#log-stats').innerHTML = `<div class="stat"><div class="stat-label">全部通联</div><div class="stat-value">${formatNumber(stats.total)}</div><div class="stat-note">累计 QSO</div></div><div class="stat"><div class="stat-label">今日通联</div><div class="stat-value">${formatNumber(stats.today)}</div><div class="stat-note">UTC 日期</div></div><div class="stat"><div class="stat-label">本月通联</div><div class="stat-value">${formatNumber(stats.this_month)}</div><div class="stat-note">UTC 自然月</div></div><div class="stat"><div class="stat-label">QSL 待处理</div><div class="stat-value">—</div><div class="stat-note">后端未提供聚合</div></div>`;
    }
    async function loadTable() {
      const target = document.querySelector('#logs-table'); target.innerHTML = '<div class="loading">加载日志...</div>';
      const data = await HamLogAPI.post('/log/list', {page: state.page, page_size: state.pageSize, keyword: state.keyword || null, band: state.band || null, mode: state.mode || null, date_from: state.dateFrom || null, date_to: state.dateTo || null, order: 'desc'});
      const items = data.items || []; const pagesTotal = Math.max(1, Math.ceil(data.total / data.page_size)); if (state.page > pagesTotal) { state.page = pagesTotal; return loadTable(); }
      target.innerHTML = `<div class="table-wrap"><table><thead><tr><th>ID</th><th>呼号</th><th>UTC 日期/时间</th><th>频率</th><th>模式</th><th>RST</th><th>QTH</th><th>设备</th><th>QSL</th><th>操作</th></tr></thead><tbody>${items.length ? items.map(item => `<tr><td>${escapeHtml(item.id)}</td><td><strong>${escapeHtml(item.Callsign)}</strong></td><td>${escapeHtml([item.Year, String(item.Month || '').padStart(2,'0'), String(item.Day || '').padStart(2,'0')].filter(Boolean).join('-'))} ${escapeHtml(item.Time || '')}</td><td>${escapeHtml(item.Freq || '-')}</td><td>${escapeHtml(item.Mode || '-')}</td><td>${escapeHtml(item.Rst_self || '-')} / ${escapeHtml(item.Rst_side || '-')}</td><td>${escapeHtml(item.QTH || '-')}</td><td>${escapeHtml(item.Device || '-')}</td><td>${item.QSL_RX || item.QSL_SEND ? '<span class="badge success">已记录</span>' : '<span class="badge">未记录</span>'}</td><td><div class="table-actions"><button class="button button-secondary button-small" data-edit="${item.id}">编辑</button><button class="button button-danger button-small" data-delete="${item.id}" data-call="${escapeHtml(item.Callsign)}">删除</button></div></td></tr>`).join('') : '<tr><td colspan="10" class="table-empty">没有符合条件的日志。</td></tr>'}</tbody></table></div><div class="pagination"><span>共 ${formatNumber(data.total)} 条 · 第 ${data.page} / ${pagesTotal} 页</span><div class="pagination-actions"><button class="button button-secondary button-small" id="prev-page"${state.page <= 1 ? ' disabled' : ''}>上一页</button><button class="button button-secondary button-small" id="next-page"${state.page >= pagesTotal ? ' disabled' : ''}>下一页</button></div></div>`;
      target.querySelectorAll('[data-edit]').forEach(button => button.onclick = async () => openEditor(await HamLogAPI.post('/log/get', {id: Number(button.dataset.edit)})));
      target.querySelectorAll('[data-delete]').forEach(button => button.onclick = async () => { if (!confirm(`确定删除 ${button.dataset.call} 的 QSO 记录？`)) return; try { await HamLogAPI.post('/log/delete', {id:Number(button.dataset.delete)}); HamLogToast.show('日志已删除'); await Promise.all([loadTable(), loadStats()]); } catch (error) { HamLogToast.error(error.message); } });
      document.querySelector('#prev-page').onclick = () => { state.page--; loadTable(); }; document.querySelector('#next-page').onclick = () => { state.page++; loadTable(); };
    }
    function readFilters() { state.keyword = document.querySelector('#log-keyword').value.trim(); state.band = document.querySelector('#log-band').value; state.mode = document.querySelector('#log-mode').value; state.dateFrom = document.querySelector('#log-from').value; state.dateTo = document.querySelector('#log-to').value; state.page = 1; loadTable().catch(error => HamLogToast.error(error.message)); }
    document.querySelector('#run-search').onclick = readFilters; document.querySelector('#log-keyword').addEventListener('input', debounce(readFilters, 350));
    document.querySelector('#reset-search').onclick = () => { state = {...state, page:1, keyword:'', band:'', mode:'', dateFrom:'', dateTo:''}; document.querySelector('#log-keyword').value=''; document.querySelector('#log-band').value=''; document.querySelector('#log-mode').value=''; document.querySelector('#log-from').value=''; document.querySelector('#log-to').value=''; loadTable(); };
    form.onsubmit = async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(form)); const id = values.id; const [year, month, day] = values.qso_date.split('-').map(Number); delete values.id; delete values.qso_date; Object.assign(values, {Year:year, Month:month, Day:day}); try { if (id) await HamLogAPI.post('/log/update', {id:Number(id), log:values}); else await HamLogAPI.post('/log/add', values); HamLogToast.show(id ? '日志已更新' : '日志已添加'); closeEditor(); await Promise.all([loadTable(), loadStats()]); } catch (error) { HamLogToast.error(error.message); } };
    await Promise.all([loadStats(), loadTable()]); if (params.get('new') === '1') openEditor();
  };
}());
