(function () {
  const pages = window.HamLogPages = window.HamLogPages || {}; const {escapeHtml, formatNumber} = HamLogUtils;
  pages.lotw = async function lotwPage(container) {
    container.innerHTML = `<div class="page-heading"><div><p class="eyebrow">ARRL Logbook of The World</p><h1>LoTW 上传</h1><p>使用 TrustedQSL 签名并上传近期通联。</p></div><span class="badge warning">需要 TQSL</span></div><section class="panel"><div class="panel-header"><div><h2>环境检查</h2><p>确认 TrustedQSL 安装与证书状态。</p></div><button class="button button-secondary button-small" id="find-tqsl">重新检查</button></div><div id="lotw-environment" class="loading">检查中...</div></section><section class="panel"><div class="panel-header"><div><h2>准备 ADIF</h2><p>上传 LoTW 前先生成符合签名流程的 ADIF。</p></div></div><form id="lotw-form"><div class="form-grid three"><label>站点位置<input name="station_location" placeholder="Mianyang" required></label><label>重复记录策略<select name="duplicate_strategy"><option value="skip">跳过</option><option value="replace">替换</option><option value="ask">询问</option></select></label><label>日期范围<input name="date_range" value="最近日志" readonly></label></div><div class="form-actions"><button class="button button-primary" type="submit">生成并上传</button></div></form></section><section class="panel" id="lotw-progress"><div class="table-empty">还没有上传任务。</div></section>`;
    const environment = document.querySelector('#lotw-environment'); const form = document.querySelector('#lotw-form'); const progress = document.querySelector('#lotw-progress'); let timer;
    async function check() { environment.innerHTML = '<div class="loading">正在查找 tqsl...</div>'; try { const tqsl = await HamLogAPI.post('/lotw/find_tqsl', {search_drives: null}); const certs = await HamLogAPI.post('/lotw/list_certs', {tqsl_path:tqsl.tqsl_path}); environment.innerHTML = `<div class="result-grid"><div class="result-item"><dt>TQSL 路径</dt><dd class="code-block" style="max-height:none;padding:7px">${escapeHtml(tqsl.tqsl_path)}</dd></div><div class="result-item"><dt>版本</dt><dd>${escapeHtml(tqsl.version || '未知')}</dd></div><div class="result-item"><dt>可用证书</dt><dd>${(certs.certs || []).length ? certs.certs.map(cert => `<span class="badge success">${escapeHtml(cert.callsign)} · ${escapeHtml(cert.station)}</span>`).join(' ') : '未发现证书'}</dd></div></div>`; return tqsl; } catch (error) { environment.innerHTML = `<div class="notice warning">${escapeHtml(error.message)}<br><span class="muted">请确认本机已安装 TrustedQSL，且服务进程可以执行 tqsl。</span></div>`; return null; } }
    document.querySelector('#find-tqsl').onclick = check;
    async function poll(taskId) { try { const status = await HamLogAPI.post('/lotw/progress', {task_id:taskId}); progress.innerHTML = `<div class="panel-header"><div><h2>上传进度</h2><p>${escapeHtml(status.message || status.status || '处理中')}</p></div><span class="badge ${status.status === 'done' ? 'success' : status.status === 'error' ? 'danger' : 'warning'}">${escapeHtml(status.status || 'pending')}</span></div><div class="result-grid"><div class="result-item"><dt>已上传</dt><dd>${formatNumber(status.uploaded)}</dd></div><div class="result-item"><dt>重复</dt><dd>${formatNumber(status.duplicates)}</dd></div><div class="result-item"><dt>错误</dt><dd>${(status.errors || []).length}</dd></div></div>`; if (!['done','error'].includes(status.status)) timer = setTimeout(() => poll(taskId), 1500); } catch (error) { clearTimeout(timer); progress.innerHTML = `<div class="notice danger">${escapeHtml(error.message)}</div>`; } }
    form.onsubmit = async event => { event.preventDefault(); const tqsl = await check(); if (!tqsl) return; try { const adif = await HamLogAPI.post('/adif/export', {}); const values = Object.fromEntries(new FormData(form)); const task = await HamLogAPI.post('/lotw/upload', {tqsl_path:tqsl.tqsl_path, station_location:values.station_location, adif_token:adif.token, duplicate_strategy:values.duplicate_strategy}); progress.innerHTML = '<div class="loading">上传任务已创建...</div>'; poll(task.task_id); } catch (error) { progress.innerHTML = `<div class="notice danger">${escapeHtml(error.message)}</div>`; } };
    await check(); return () => clearTimeout(timer);
  };
}());
