(function () {
  const pages = window.HamLogPages = window.HamLogPages || {}; const {escapeHtml} = HamLogUtils;
  pages.qrz = async function qrzPage(container) {
    container.innerHTML = `<div class="page-heading"><div><p class="eyebrow">Callsign lookup</p><h1>QRZ 查询</h1><p>查询呼号公开资料、QSL 状态与电台简介。</p></div><span class="badge">QRZ.com</span></div><section class="panel"><form class="inline-form" id="qrz-form"><label>呼号<input name="callsign" placeholder="例如 BA8AQA" maxlength="20" required autocapitalize="characters"></label><label style="max-width:160px">查询模式<select name="login"><option value="false">公开资料</option><option value="true">登录态</option></select></label><button class="button button-primary" type="submit">查询</button></form></section><section class="panel" id="qrz-result"><div class="table-empty">输入一个呼号开始查询。</div></section><section class="panel"><div class="panel-header"><div><h2>QRZ 账户</h2><p>凭据必须使用 AES-256 加密存储，页面不会保留密码。</p></div><button class="button button-danger button-small" id="clear-qrz">清除凭据</button></div><form class="inline-form" id="qrz-credential-form"><label>用户名<input name="username" autocomplete="username" required></label><label>密码<input name="password" type="password" autocomplete="current-password" required></label><button class="button button-secondary" type="submit">加密保存</button></form></section>`;
    const form = document.querySelector('#qrz-form'); const result = document.querySelector('#qrz-result');
    form.elements.callsign.oninput = event => { event.target.value = event.target.value.toUpperCase(); };
    form.onsubmit = async event => { event.preventDefault(); const callsign = form.elements.callsign.value.trim().toUpperCase(); result.innerHTML = '<div class="loading">正在查询 QRZ...</div>'; try { const data = await HamLogAPI.post('/qrz/lookup', {callsign, login: form.elements.login.value === 'true'}); result.innerHTML = `<div class="panel-header"><div><p class="eyebrow">${escapeHtml(data.country || 'Callsign profile')}</p><h2 class="panel-title">${escapeHtml(data.callsign || callsign)}</h2><p>${data.url ? `<a href="${escapeHtml(data.url)}" target="_blank" rel="noreferrer">在 QRZ.com 打开 ↗</a>` : ''}</p></div><span class="badge success">已找到</span></div><div class="result-grid"><div class="result-item"><dt>姓名</dt><dd>${escapeHtml(data.name || '未公开')}</dd></div><div class="result-item"><dt>QTH</dt><dd>${escapeHtml(data.qth || '未公开')}</dd></div><div class="result-item"><dt>网格</dt><dd>${escapeHtml(data.grid || '未公开')}</dd></div><div class="result-item"><dt>执照等级</dt><dd>${escapeHtml(data.license_class || '未公开')}</dd></div><div class="result-item"><dt>LoTW</dt><dd>${data.lotw ? '<span class="badge success">支持</span>' : '<span class="badge">未标注</span>'}</dd></div><div class="result-item"><dt>eQSL</dt><dd>${data.eqsl ? '<span class="badge success">支持</span>' : '<span class="badge">未标注</span>'}</dd></div></div>${data.bio ? `<div style="margin-top:20px"><p class="eyebrow">Biography</p><p class="muted" style="line-height:1.7;margin:0">${escapeHtml(data.bio)}</p></div>` : ''}${data.image_url ? `<div style="margin-top:20px"><img src="${escapeHtml(data.image_url)}" alt="${escapeHtml(data.callsign || callsign)}" style="max-width:180px;max-height:180px;object-fit:cover;border:1px solid var(--line);border-radius:4px"></div>` : ''}`; } catch (error) { result.innerHTML = `<div class="notice danger">${escapeHtml(error.message)}<br><span class="muted">QRZ 查询可能受网络或站点访问限制影响。</span></div>`; } };
    const credentialForm = document.querySelector('#qrz-credential-form');
    credentialForm.onsubmit = async event => { event.preventDefault(); try { await HamLogAPI.post('/qrz/set_credential', {...Object.fromEntries(new FormData(credentialForm)), encrypt:true}); credentialForm.reset(); form.elements.login.value = 'true'; HamLogToast.show('QRZ 凭据已加密保存'); } catch (error) { HamLogToast.error(error.message); } };
    document.querySelector('#clear-qrz').onclick = async () => { if (!confirm('确定清除已保存的 QRZ 凭据？')) return; try { await HamLogAPI.post('/qrz/clear_credential'); form.elements.login.value = 'false'; HamLogToast.show('QRZ 凭据已清除'); } catch (error) { HamLogToast.error(error.message); } };
  };
}());
