(function () {
  const pages = window.HamLogPages = window.HamLogPages || {}; const {escapeHtml} = HamLogUtils;
  pages.settings = async function settingsPage(container) {
    const settings = await HamLogAPI.post('/settings/get_all'); HamLogStore.update({settings});
    container.innerHTML = `<div class="page-heading"><div><p class="eyebrow">Station profile</p><h1>本台设置</h1><p>维护本台身份、默认通联参数与界面偏好。</p></div></div><form id="settings-form"><section class="panel"><div class="panel-header"><div><h2>电台身份</h2><p>用于日志录入、ADIF 与 QSL 数据绑定</p></div></div><div class="form-grid"><label>本台呼号<input name="my_callsign" value="${escapeHtml(settings.my_callsign || '')}" style="text-transform:uppercase"></label><label>姓名<input name="my_name" value="${escapeHtml(settings.my_name || '')}"></label><label>QTH<input name="my_qth" value="${escapeHtml(settings.my_qth || '')}"></label><label>网格定位<input name="my_grid" value="${escapeHtml(settings.my_grid || '')}" style="text-transform:uppercase"></label></div></section><section class="panel"><div class="panel-header"><div><h2>通联默认值</h2><p>新建 QSO 时可使用的常用参数</p></div></div><div class="form-grid"><label>默认模式<select name="default_mode"><option value="">不预设</option>${['SSB','CW','FM','AM','FT8','FT4','RTTY','DIGI'].map(mode => `<option${settings.default_mode === mode ? ' selected' : ''}>${mode}</option>`).join('')}</select></label><label>默认功率<input name="default_power" value="${escapeHtml(settings.default_power || '')}" placeholder="5W"></label><label>默认设备<input name="default_device" value="${escapeHtml(settings.default_device || '')}" placeholder="FT-817"></label><label>默认频率<input name="default_freq" value="${escapeHtml(settings.default_freq || '')}" placeholder="14.074MHz"></label></div></section><section class="panel"><div class="panel-header"><div><h2>显示与行为</h2><p>仅影响当前 HamLog 工作界面</p></div></div><div class="form-grid three"><label>主题<select name="theme"><option value="light"${settings.theme !== 'dark' ? ' selected' : ''}>浅色</option><option value="dark"${settings.theme === 'dark' ? ' selected' : ''}>深色</option></select></label><label>日志每页数量<select name="page_size">${[25,50,100].map(size => `<option value="${size}"${String(settings.page_size || '25') === String(size) ? ' selected' : ''}>${size} 条</option>`).join('')}</select></label><label>默认时区<select name="timezone"><option value="UTC"${settings.timezone !== 'local' ? ' selected' : ''}>UTC</option><option value="local"${settings.timezone === 'local' ? ' selected' : ''}>本地时间</option></select></label></div><div class="form-actions"><button class="button button-primary" type="submit">保存设置</button></div></section></form>`;
    const form = document.querySelector('#settings-form'); const theme = form.elements.theme;
    theme.onchange = () => { document.body.dataset.theme = theme.value; };
    form.elements.my_callsign.oninput = event => { event.target.value = event.target.value.toUpperCase(); };
    form.elements.my_grid.oninput = event => { event.target.value = event.target.value.toUpperCase(); };
    form.onsubmit = async event => { event.preventDefault(); const items = Object.fromEntries(new FormData(form)); try { await HamLogAPI.post('/settings/set_many', {items}); HamLogStore.update({settings: items}); localStorage.setItem('hamlog.theme', items.theme); document.body.dataset.theme = items.theme; HamLogToast.show('设置已保存'); } catch (error) { HamLogToast.error(error.message); } };
  };
}());
